# DO NOT EDIT THIS FILE!
#
# Python module Manipulation__POA generated by omniidl

import omniORB
omniORB.updateModule("Manipulation__POA")

# ** 1. Stub files contributing to this module
import TrajectoryPlanner_idl

# ** 2. Sub-modules

# ** 3. End
