# DO NOT EDIT THIS FILE!
#
# Python module Manipulation generated by omniidl

import omniORB
omniORB.updateModule("Manipulation")

# ** 1. Stub files contributing to this module
import TrajectoryPlanner_idl

# ** 2. Sub-modules

# ** 3. End
